apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: nliza-bootiful-client
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: bootiful-client-nliza
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.flavours: spring-boot_spring-cloud-gateway-server
    app.kubernetes.io/component: run
    carto.run/workload-name: nliza-bootiful-client
spec:
  template:
    metadata:
      annotations:
        apps.tanzu.vmware.com/correlationid: harbor.services.tanzu.rocks/labs/local-source:workshop-nliza-bootiful-client?sub_path=/
        autoscaling.knative.dev/minScale: "1"
        boot.spring.io/version: 3.2.1
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/spring-boot
          spring-boot-convention/spring-boot-web
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
        local-source-proxy.apps.tanzu.vmware.com: harbor.services.tanzu.rocks/labs/local-source:workshop-nliza-bootiful-client@sha256:2d2301b708ed8dfb540bbc315eb3a2702c08c494301a0b5ccb4fde207406cc1f
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: bootiful-client-nliza
        apps.tanzu.vmware.com/auto-configure-actuators: "true"
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: nliza-bootiful-client
        conventions.carto.run/framework: spring-boot
        tanzu.app.live.view: "true"
        tanzu.app.live.view.application.flavours: spring-boot_spring-cloud-gateway-server
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: cloud
        - name: JAVA_TOOL_OPTIONS
          value: -Dserver.port="8080"
        image: harbor.services.tanzu.rocks/labs/supply-chain/nliza-bootiful-client-workshop@sha256:61e38f2544714b6b140218f06e8c898234dfb49710f9fc1fa9be5168f400bc8f
        name: workload
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
      serviceAccountName: default

