apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: angular-frontend-james
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: angular-frontend-james
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: angular-frontend-james
spec:
  template:
    metadata:
      annotations:
        apps.tanzu.vmware.com/correlationid: harbor.services.tanzu.rocks/labs/local-source:delta-angular-frontend-james?sub_path=/
        autoscaling.knative.dev/minScale: "1"
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
        local-source-proxy.apps.tanzu.vmware.com: harbor.services.tanzu.rocks/labs/local-source:delta-angular-frontend-james@sha256:2a8bfdeed8fdb6efaf7580a9800d6adb41af7faa9f565c61671de39ecc9f081c
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: angular-frontend-james
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: angular-frontend-james
    spec:
      containers:
      - image: harbor.services.tanzu.rocks/labs/supply-chain/angular-frontend-james-delta@sha256:f7a7217f4fbb2c990b7c8b2c1acfc1e30322d631e7d208fddfc6428c6373a5f3
        name: workload
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
      serviceAccountName: default

