apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: react-frontend-nliza
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: react-frontend-nliza
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: react-frontend-nliza
spec:
  template:
    metadata:
      annotations:
        apps.tanzu.vmware.com/correlationid: harbor.services.tanzu.rocks/labs/local-source:demo-react-frontend-nliza?sub_path=/
        autoscaling.knative.dev/minScale: "1"
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
        local-source-proxy.apps.tanzu.vmware.com: harbor.services.tanzu.rocks/labs/local-source:demo-react-frontend-nliza@sha256:c0263384a733ca00f90776c6e27cd4ff7c5214f4a8a6437e2dba945dc3eaaf5c
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: react-frontend-nliza
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: react-frontend-nliza
    spec:
      containers:
      - image: harbor.services.tanzu.rocks/labs/supply-chain/react-frontend-nliza-demo@sha256:75a773796db4bf2556833950e3ab32bc89069010a2e50af2ec9ed2e2431ef1ab
        name: workload
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
      serviceAccountName: default

